services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    blog.twig.extension:
        class: BlogBundle\Twig\Extension\BlogExtension
        tags:
            - { name: twig.extension }
